//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokterPraktekV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSpecialist
    {
        public int ID { get; set; }
        public int SpecialtyID { get; set; }
        public string DoctorID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
