//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokterPraktekV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPicture
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public string ImageType { get; set; }
        public byte[] ImageContent { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
